### PR TITLE
Command bar and sidebar fixes

### LINKED ISSUE #781: Command bar fixes
The command bar currently works, but is not very clear.

For example, an option simply labeled "Enable" appears there, which actually refers to the "Fast mode toggle". this should be fixed so that by looking at the command bar, it becomes clear what the option is meant to do

for addresses, it should be clear which wallet they come from (and perhaps what their index is within that wallet), and if they have an alias or not

### PR DESCRIPTION
**Pull request by DavideSilva**
Why:
* To solve #826 and partially fix #781

How:
* Including the wallet's name when displaying in the command bar
  switcher
* Adding "fast mode" text to the command bar options to toggle fast mode
* Fixing UI update issues when changing the wallet from the command bar
  and toggling fast mode

fast mode
wallet name

### CODE REVIEW

File: gui/src/store/useWallets.ts [hunk 1]
```diff
@@ -76,7 +76,7 @@ const store: StateCreator<Store> = (set, get) => ({
         ...(addresses || []).map(({ key, address }) => {
           return {
             id: `${actionId}/${wallet.name}/${key}`,
-            text: address,
+            text: `${wallet.name}/${address}`,
```
Comment (naps62) [inline gui/src/store/useWallets.ts:79]:
```suggestion
            text: `${wallet.name}/${alias || address}`,
```

File: gui/src/store/useWallets.ts [hunk 2]
```diff
@@ -76,7 +76,7 @@ const store: StateCreator<Store> = (set, get) => ({
         ...(addresses || []).map(({ key, address }) => {
```
Comment (naps62) [inline gui/src/store/useWallets.ts:76]:
```suggestion
        ...(addresses || []).map(({ key, address, alias }) => {
```

File: gui/src/store/useWallets.ts (hunk 1 above)
Comment (naps62) [reply gui/src/store/useWallets.ts:79]: I'm assuming this could work too?

File: gui/src/components/QuickAddressSelect.tsx [hunk 3]
```diff
@@ -29,6 +29,7 @@ export function QuickAddressSelect() {
   return (
     <Select
       key={currentWallet.name}
+      value={getCurrentPath(currentWallet, addresses)}
```
Comment (naps62) [inline gui/src/components/QuickAddressSelect.tsx:32]: I don't have enough context to remember, can you explain why this is needed?
Seeing both `value` and `defaultValue` as props seems weird

File: gui/src/components/QuickFastModeToggle.tsx [hunk 4]
```diff
@@ -15,6 +15,7 @@ export function QuickFastModeToggle() {
     <div className="flex items-center space-x-2">
       <Switch
         defaultChecked={fastMode}
+        checked={fastMode}
```
Comment (naps62) [inline gui/src/components/QuickFastModeToggle.tsx:18]: same as above here. `defaultXXX` is different from `XXX`, in the sense that it won't update if the value changes (on purpose). this seems suspicious

File: gui/src/components/QuickAddressSelect.tsx (hunk 3 above)
Comment (DavideSilva) [reply gui/src/components/QuickAddressSelect.tsx:32]: setting `value` is needed to update the displayed value when we change the address from the command bar, otherwise it wouldn't update

Comment (naps62) [reply gui/src/components/QuickAddressSelect.tsx:32]: no, what you need is to force a re-render of the react object
setting `value` explicitly will conflict with the ability to use the input itself

possibly what you want is to set a `key={...}` to make sure it re-renders that component when some outside value change, but still have it react to updates in the select itself

Comment (DavideSilva) [reply gui/src/components/QuickAddressSelect.tsx:32]: from what I tested, it doesn't seem to conflict with anything, I can still change the value from clicking the ui or by using the command bar

Comment (DavideSilva) [reply gui/src/components/QuickAddressSelect.tsx:32]: ok, changing the `key` value from `currentWallet.name` to getting the current path seems to also work

**Review by naps62 — APPROVED** [review]
